/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ThirtyFive } from "./ThirtyFive";

export { ThirtyFive__factory } from "./factories/ThirtyFive__factory";
